# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Cache principal de l'application
    cache:
        app: cache.adapter.filesystem

    # Session Symfony
    session:
        handler_id: 'cache.app'
    #esi: true
    #fragments: true
    csrf_protection: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
            cookie_secure: auto        # true si HTTPS
            cookie_samesite: lax
