vich_uploader:
    db_driver: orm
    mappings:
        user_dashboard:
            uri_prefix: /uploads/images/dashboard
            upload_destination: '%kernel.project_dir%/public/uploads/images/dashboard'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
