# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EventSubscriber\SecurityEventSubscriber:
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\LoginSuccessEvent, method: onLoginSuccess }
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\LoginFailureEvent, method: onLoginFailure }
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\LogoutEvent, method: onLogout }
            - { name: kernel.event_listener, event: Symfony\Component\Security\Core\Event\PasswordAuthenticatedEvent, method: onPasswordChanged }
            # pour register si tu as un Event custom
            #- { name: kernel.event_listener, event: App\Event\UserRegisteredEvent, method: onUserRegistered }

    App\EventSubscriber\NeedEventSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }

    App\EventSubscriber\ActionEventSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }
    
    App\EventSubscriber\SubscriptionEventSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }
    
    App\EventSubscriber\NotificationEventSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }
